#!/bin/bash
# generate_pr_comment.sh - Generate markdown PR comment from test results
# Usage: ./generate_pr_comment.sh <current_results.json> <analysis.json>
# Output: Markdown text to stdout

set -e

CURRENT="$1"
ANALYSIS="$2"

if [[ ! -f "$CURRENT" ]]; then
    echo "❌ **Error:** Test results not found"
    exit 1
fi

# Extract current test summary
PASSED=$(jq -r '.cargo_test.passed' "$CURRENT")
FAILED=$(jq -r '.cargo_test.failed' "$CURRENT")
IGNORED=$(jq -r '.cargo_test.ignored' "$CURRENT")
DURATION=$(jq -r '.duration_seconds' "$CURRENT")
FIX_PASSED=$(jq -r '.fixture_results.passed' "$CURRENT")
FIX_FAILED=$(jq -r '.fixture_results.failed' "$CURRENT")
FIX_SKIPPED=$(jq -r '.fixture_results.skipped' "$CURRENT")

# Extract analysis results
HAS_BASELINE=$(jq -r '.has_baseline // false' "$ANALYSIS")
REGRESSION_COUNT=$(jq -r '.regression_count // 0' "$ANALYSIS")
FIX_COUNT=$(jq -r '.fix_count // 0' "$ANALYSIS")
DELTA_PASSED=$(jq -r '.delta_passed // 0' "$ANALYSIS")
DELTA_FAILED=$(jq -r '.delta_failed // 0' "$ANALYSIS")
BASELINE_TIMESTAMP=$(jq -r '.baseline.timestamp // "N/A"' "$ANALYSIS")

# Determine status
if [[ "$REGRESSION_COUNT" -gt 0 ]]; then
    STATUS_EMOJI="❌"
    STATUS_TEXT="Regressions detected!"
    elif [[ "$FIX_COUNT" -gt 0 ]]; then
    STATUS_EMOJI="🎉"
    STATUS_TEXT="Tests fixed!"
    elif [[ "$FAILED" -eq 0 ]]; then
    STATUS_EMOJI="✅"
    STATUS_TEXT="All tests passing!"
else
    STATUS_EMOJI="⚠️"
    STATUS_TEXT="Some tests failing (no new regressions)"
fi

# Format duration
DURATION_FMT=$(printf "%.2f" "$DURATION")

# Generate markdown
cat << EOF
## ${STATUS_EMOJI} Test Results

**Status:** ${STATUS_TEXT}

### Test Summary

| Metric | Count | Delta |
|--------|-------|-------|
| ✅ Passed | ${PASSED} | ${DELTA_PASSED:+$([ "$DELTA_PASSED" -gt 0 ] && echo "+")${DELTA_PASSED}} |
| ❌ Failed | ${FAILED} | ${DELTA_FAILED:+$([ "$DELTA_FAILED" -gt 0 ] && echo "+")${DELTA_FAILED}} |
| ⏭️ Ignored | ${IGNORED} | - |
| ⏱️ Duration | ${DURATION_FMT}s | - |

### Fixture Results

| Metric | Count |
|--------|-------|
| ✅ Passed | ${FIX_PASSED} |
| ❌ Failed | ${FIX_FAILED} |
| ⏭️ Skipped | ${FIX_SKIPPED} |

EOF

# Show baseline info
if [[ "$HAS_BASELINE" == "true" ]]; then
    echo "<details>"
    echo "<summary>📊 Compared against baseline from ${BASELINE_TIMESTAMP}</summary>"
    echo ""
    
    # Show regressions
    if [[ "$REGRESSION_COUNT" -gt 0 ]]; then
        echo "### 🔴 Regressions (${REGRESSION_COUNT})"
        echo ""
        echo "These tests were passing in the baseline but are now failing:"
        echo ""
        jq -r '.regressions[] | "- **\(.name)** (\(.id))\n  > \(.error)"' "$ANALYSIS"
        echo ""
    fi
    
    # Show fixes
    if [[ "$FIX_COUNT" -gt 0 ]]; then
        echo "### 🟢 Fixed (${FIX_COUNT})"
        echo ""
        echo "These tests were failing in the baseline but are now passing:"
        echo ""
        jq -r '.fixes[] | "- **\(.name)** (\(.id))"' "$ANALYSIS"
        echo ""
    fi
    
    if [[ "$REGRESSION_COUNT" -eq 0 && "$FIX_COUNT" -eq 0 ]]; then
        echo ""
        echo "_No changes from baseline._"
        echo ""
    fi
    
    echo "</details>"
else
    echo ""
    echo "> ℹ️ No baseline established yet. Baseline will be created when this PR merges to main."
fi

echo ""
echo "---"
echo "*Generated by [test workflow](../actions/workflows/test.yml) • Commit: \`${GITHUB_SHA:0:7}\`*"
